---
- name: Creating docker group
  group: name=docker state=present
    
- name: Docker proxy configuration
  file:
    name: /etc/systemd/system/docker.service.d/
    owner: root
    group: root
    state: directory
    recurse: yes
  when: proxy != ""

- name: Docker proxy configuration
  template: src=http-proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf
  when: proxy != ""

- name: Docker network daemon configuration
  copy: src=docker-network dest=/etc/sysconfig/docker-network

- name: Docker storage configuration
  template: src=docker-storage dest=/etc/sysconfig/docker-storage

- name: Disabling selinux
  selinux: state=disabled
  register: selinux
  when: disable_selinux|bool == True

- name: Enable ntpd service
  service: 
    name: ntpd
    enabled: yes
    state: started

- name: Enable docker service
  service: 
    name: docker 
    enabled: yes

