---
- name: Download docker compose
  get_url: url=https://github.com/docker/compose/releases/download/1.7.0/run.sh
    dest=/usr/local/bin/docker-compose

- name: Setup docker compose
  file: name=/usr/local/bin/docker-compose state=file mode=755
