---
# tasks file for gchiesa.docker

- include: yum.yml
- include: firewall.yml
- include: docker.yml
- include: docker-folders.yml
- include: docker-compose.yml
- include: ansible-docker.yml
- include: reboot.yml

- name: Starting docker service
  service:
    enabled: yes 
    name: docker 
    state: restarted

- name: Iptables save
  shell: iptables-save > "{{ iptables_config }}"
