# reboot the machine if the kernel has changed
- name: Check for reboot hint.
  shell: k=$(ls -v /boot/vmlinuz-*| tail -1); if [ "${k#*vmlinuz-}" != "$(uname -r)" ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Rebooting ...
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  when: reboot_hint.stdout.find("reboot") != -1 or selinux.changed
  register: reboot

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false
  when: reboot_hint.stdout.find("reboot") != -1 or selinux.changed
