---
- name: Install yum required packages
  yum: name={{ item }} state=installed
  with_items:
    - yum-utils
    - net-tools
    - nc
    - iptables-services
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum

- name: Remove firewalld service
  yum: name=firewalld state=removed
  tags: yum
  
- name: Config addons
  command: yum-config-manager --enable ol7_addons
  tags: yum

- name: Enable UEK4 repo
  copy: src=files/public-yum-ol7-uek4.repo dest=/etc/yum.repos.d/public-yum-ol7-uek4.repo
  tags: yum

- name: Install docker engine
  yum: name="docker-engine" state=installed
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum
