---
# - name: Update system
#   yum: name=* state=latest
#   environment:
#     http_proxy: "{{ proxy }}"
#     https_proxy: "{{ proxy }}"

- name: Install yum-utils
  yum: name="yum-utils" state=installed
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum

- name: Config addons
  command: yum-config-manager --enable ol7_addons
  tags: yum

- name: Enable UEK4 repo
  copy: src=files/public-yum-ol7-uek4.repo dest=/etc/yum.repos.d/public-yum-ol7-uek4.repo
  tags: yum

- name: Install docker engine
  yum: name="docker-engine" state=installed
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum
