---
- name: Install yum required packages
  yum: name={{ item }} state=installed
  with_items:
    - yum-utils
    - net-tools
    - nc
    - iptables-services
    - ntp
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum

- name: Remove firewalld service
  yum: name=firewalld state=removed
  tags: yum

- include: yum_oel.yml
  when: ansible_distribution == 'OracleLinux'

- include: yum_centos.yml
  when: ansible_distribution == 'CentOS'
