---
- name: Config addons
  command: yum-config-manager --enable ol7_addons
  tags: yum

- name: Enable UEK4 repo
  copy: src=files/public-yum-ol7-uek4.repo dest=/etc/yum.repos.d/public-yum-ol7-uek4.repo
  tags: yum

- name: Install docker engine
  yum: 
    name: "{{ item }}"
    state: installed
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tags: yum
  with_items: 
    - iptables-services
    - docker_engine 


